# Generated by Django 5.1.6 on 2025-02-16 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date_heure', models.DateTimeField()),
                ('lieu', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('capacite_max', models.IntegerField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('billets_disponibles', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['date_heure'],
            },
        ),
    ]
