# Generated by Django 5.1.6 on 2025-02-19 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evenements', '0004_evenement_evenementlibre'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='prix',
            field=models.IntegerField(default=20000),
        ),
    ]
