# Generated by Django 5.1.6 on 2025-02-28 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeOrganisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_entreprise', models.CharField(max_length=255)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('numero_cni', models.CharField(max_length=50)),
                ('photo_cni', models.ImageField(blank=True, null=True, upload_to='cni/')),
                ('types_evenements', models.JSONField(default=list)),
                ('taille_evenements', models.CharField(max_length=50)),
                ('mode_financement', models.CharField(max_length=50)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('ACCEPTE', 'Accepté'), ('REFUSE', 'Refusé')], default='EN_ATTENTE', max_length=20)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('commentaire_admin', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='demande_organisateur', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
