# Generated by Django 5.1.6 on 2025-03-02 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_messages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandeorganisateur',
            name='types_evenements',
            field=models.CharField(max_length=50),
        ),
    ]
