# Generated by Django 5.1.6 on 2025-03-02 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_messages', '0002_alter_demandeorganisateur_types_evenements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandeorganisateur',
            name='types_evenements',
            field=models.JSONField(default=list),
        ),
    ]
