# Generated by Django 5.1.6 on 2025-02-17 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_prenom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='prenom',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
