# Generated by Django 5.1.6 on 2025-02-16 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Billet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type_billet', models.CharField(choices=[('GRATUIT', 'Gratuit'), ('PAYANT', 'Payant')], default='GRATUIT', max_length=20)),
                ('prix', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('date_achat', models.DateTimeField(auto_now_add=True)),
                ('code_qr', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('valide', models.BooleanField(default=False)),
                ('est_annule', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['date_achat'],
            },
        ),
    ]
