# Generated by Django 5.1.6 on 2025-02-18 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billets', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billet',
            name='participant',
        ),
    ]
