# Generated by Django 5.1.6 on 2025-03-02 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketpurchase',
            name='session_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
